[versions]
jacksonDatabindVersion = "2.17.2"

kotestVersion = "5.9.1"
kotestSpringVersion = "1.3.0"

[libraries]
jacksonDatabind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jacksonDatabindVersion" }

kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotestVersion" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotestVersion" }
kotest-property = { module = "io.kotest:kotest-property", version.ref = "kotestVersion" }
kotest-extensions-spring = { module = "io.kotest.extensions:kotest-extensions-spring", version.ref = "kotestSpringVersion" }