#spring.application.name=sender-spring-boot-starter
spring:
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    topic: test-topic
    producer:
      acks: all
      retries: 5
      client:
        id: sender