spring:
  application:
    name: sender-spring-boot-starter
  kafka:
    enabled: true
    bootstrap-servers: localhost:9092
    topic: test-topic
    numPartitions: 1
    replicationFactor: 1
    producer:
      acks: all
      retries: 5
      client:
        id: sender